export const mockAiService = {
  generateText: async (): Promise<string> => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        // ✅ CHANGED: Set to false to stop random crashes
        const shouldFail = false; 
        
        if (shouldFail) {
          reject(new Error("AI service is temporarily unavailable."));
        } else {
          resolve(" This is a continuation generated by the AI. It demonstrates how the editor appends content dynamically.");
        }
      }, 1500);
    });
  }
};